# Autoprefixer will make sure your CSS works with these browsers
BROWSERS:
    - "last 2 versions"
    - "ie >= 9"


# Babel Config
BABEL:

    presets:
        - "es2015"


# Browserify Configuration
BROWSERIFY:

    # Bootstrap
    bootstrap:  "src/app/app.js"

    # Shorcuts
    shortcuts:
        - type: "dir"
          name: "helpers"
          path: "./src/app/helpers"

        - type: "dir"
          name: "libs"
          path: "./src/app/libs"

        - type: "dir"
          name: "components"
          path: "./src/app/views/_shared/components"


# Paths to Sass libraries, which can then be loaded with @import
SASS:

    # Path to source files
    source: "src/scss"

    # Path to output files
    output: "dist/css"

    # Path to import files
    import:
        - "bower_components/foundation-sites/scss"
        - "bower_components/motion-ui/src"
        - "bower_components/mdi/scss"

# Gulp will reference these paths when it copies files
PATHS:

    # Path to source folder
    app: "src/app"

    # Path to dist folder
    dist: "dist"

    # Paths to Javascript vendors
    vendors:
        - "bower_components/jquery/dist/jquery.min.js"
        - "bower_components/underscore/underscore-min.js"
        - "bower_components/backbone/backbone-min.js"
        - "bower_components/backbone.controller/backbone.controller.js"
        - "bower_components/what-input/what-input.min.js"
        - "bower_components/foundation-sites/dist/foundation.min.js"
        - "bower_components/foundation-datepicker/js/foundation-datepicker.min.js"
        - "bower_components/motion-ui/dist/motion-ui.min.js"
        - "bower_components/slick/dist/slick.min.js"
        - "bower_components/Sortable/Sortable.min.js"
        - "bower_components/moment/min/moment.min.js"
        #- "bower_components/moment/min/locales.min.js"
        - "bower_components/jquery.serializeJSON/jquery.serializejson.min.js"
        - "bower_components/jquery.cookie/jquery.cookie.js"
        - "bower_components/purl/purl.js"
        - "bower_components/jquery-sticky/jquery.sticky.js"
        - "bower_components/blueimp-file-upload/js/vendor/jquery.ui.widget.js"
        - "bower_components/blueimp-load-image/js/load-image.all.min.js"
        - "bower_components/blueimp-canvas-to-blob/js/canvas-to-blob.min.js"
        - "bower_components/blueimp-file-upload/js/jquery.iframe-transport.js"
        - "bower_components/blueimp-file-upload/js/jquery.fileupload.js"
        - "bower_components/blueimp-file-upload/js/jquery.fileupload-process.js"
        - "bower_components/blueimp-file-upload/js/jquery.fileupload-image.js"
        - "bower_components/teamdf/jquery-number/jquery.number.min.js"
        - "bower_components/select2/dist/js/select2.min.js"
        - "bower_components/select2/dist/js/i18n/es.js"

    # Paths to JavaScript application into one file
    javascript:
        - "src/**/*.js"
